version: 0.2
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      php: 8.2
  pre_build:
    on-failure: ABORT
    commands:
      - echo 'Logging into Amazon ECR ...'
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY
  build:
    on-failure: ABORT
    commands:
      - echo 'Building...'
      - echo "IMAGE: $IMAGE"
      - echo "IMAGE_TAG: $IMAGE_TAG"
      - echo "REPOSITORY: $REPOSITORY"
      - echo "Full docker tag command: docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG"
      - docker build -t $IMAGE .
      - docker tag $IMAGE:$IMAGE_TAG $REPOSITORY/$IMAGE:$IMAGE_TAG
  post_build:
    on-failure: ABORT
    commands:
      - docker images ls -a
      - docker push $REPOSITORY/$IMAGE:$IMAGE_TAG
    

